"""empty message

Revision ID: 5f842e784370
Revises: a137e58c6163
Create Date: 2024-09-17 19:40:45.390256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f842e784370'
down_revision: Union[str, None] = 'a137e58c6163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating_choice', 'looser_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating_choice', 'looser_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
