"""empty message

Revision ID: 95ba7a146f74
Revises: 64b6f6c862ab
Create Date: 2024-09-10 22:56:43.465399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95ba7a146f74'
down_revision: Union[str, None] = '64b6f6c862ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('choices', postgresql.ARRAY(sa.UUID()), nullable=False))
    op.drop_constraint('fk_rating_prev_choice', 'rating', type_='foreignkey')
    op.drop_constraint('fk_rating_cur_choice', 'rating', type_='foreignkey')
    op.drop_column('rating', 'items')
    op.drop_column('rating', 'cur_choice_id')
    op.drop_column('rating', 'prev_coice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('prev_coice_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('rating', sa.Column('cur_choice_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('rating', sa.Column('items', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_rating_cur_choice', 'rating', 'rating_choice', ['cur_choice_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_rating_prev_choice', 'rating', 'rating_choice', ['prev_coice_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('rating', 'choices')
    # ### end Alembic commands ###
