"""empty message

Revision ID: 95ed7b2fc0a0
Revises: 2bb2f5852ebd
Create Date: 2024-08-15 13:08:27.443369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ed7b2fc0a0'
down_revision: Union[str, None] = '2bb2f5852ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prohibited_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_prohibited_tokens_created_by_user', 'prohibited_tokens', 'user', ['created_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_prohibited_tokens_updated_by_user', 'prohibited_tokens', 'user', ['updated_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('rating', sa.Column('prev_coice_id', sa.UUID(), nullable=True))
    op.drop_constraint('fk_rating_prev_choice', 'rating', type_='foreignkey')
    op.create_foreign_key('fk_rating_prev_choice', 'rating', 'rating_choice', ['prev_coice_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('rating', 'prev_choice_id')
    op.create_foreign_key('fk_user_updated_by_user', 'user', 'user', ['updated_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_user_created_by_user', 'user', 'user', ['created_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_created_by_user', 'user', type_='foreignkey')
    op.drop_constraint('fk_user_updated_by_user', 'user', type_='foreignkey')
    op.add_column('rating', sa.Column('prev_choice_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_rating_prev_choice', 'rating', type_='foreignkey')
    op.create_foreign_key('fk_rating_prev_choice', 'rating', 'rating_choice', ['prev_choice_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('rating', 'prev_coice_id')
    op.drop_constraint('fk_prohibited_tokens_updated_by_user', 'prohibited_tokens', type_='foreignkey')
    op.drop_constraint('fk_prohibited_tokens_created_by_user', 'prohibited_tokens', type_='foreignkey')
    op.drop_table('prohibited_tokens')
    # ### end Alembic commands ###
